version: '3'
services:
  logstash:
    image: docker-logstash:latest
    container_name: logstash
    volumes:
      - ${PWD}/pipeline:/usr/share/logstash/pipeline
      - ${PWD}/config:/usr/share/logstash/config/
      - ${PWD}/config/logstash-full.yml:/usr/share/logstash/config/logstash.yml:ro
    ports:
      - 5042:5042
      - 9600:9600
    networks:
      - logstash
networks:
  logstash:
    external:
      name: elk