apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: eckelastic
  namespace: elastic-system
spec:
  version: 7.16.2
  http:
    service:
      spec:
        type: LoadBalancer
    tls:
      selfSignedCertificate:
        disabled: true
  count: 1
  elasticsearchRef:
    name: eckelastic