version: '3'
services:
  kibana:
    image: docker-kibana:latest
    container_name: kibana
    volumes:
      - $PWD/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - kibana
networks:
  kibana:
    external:
      name: elk