version: '3'
services:
  filebeat:
    image: docker-filebeat:latest
    container_name: filebeat
    volumes:
      - $PWD/filebeat.yml:/usr/share/filebeat/config/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    user: root
    networks:
      - filebeat
networks:
  filebeat:
    external:
      name: elk